### ISSUE TITLE
Dot in repository name 

### ISSUE THREAD

**Issue by mohfunk** [Priv-Page/privpage#11]
I had issues when using privpage on a repository that has a dot **`.`** in its name. 
(e.g. [mohfunk/moh.page](https://github.com/mohfunk/moh.page))

It worked as expected when I changed the repo name, please consider addressing this problem.

**Comment by j8r** [comment]
I'm not sure how to solve it: the dot is used to separate subdomains.
Sub-subdomaims cannot have Let's Encrypt certificates (double wildcards not allowed).

**Comment by mohfunk** [comment]
https://github.com/Priv-Page/privpage/blob/48ff8e0a34e29cfe779c50d26f16c9c2a817a298/src/user_repository.cr#L40
Is it possible to remove the **`.`** character here?
So `OWNER--REPOXYZ.github.privpage.net` would be the URL for  `git@github.com/OWNER/REPO.XYZ`

**Comment by j8r** [comment]
No, because the site will be the same for `OWNER/REPOXYZ` and `OWNER/REPO.XYZ`, but also anywhere the dot is, like `OWNER/R.EPOXYZ`, and `OWNER/.R.EPOXY.Z.`.

There is no wah PrivPage can now where the dot is.

**Comment by j8r** [comment]
No, because the site will be the same for `OWNER/REPOXYZ` and `OWNER/REPO.XYZ`, but also anywhere the dot is, like `OWNER/R.EPOXYZ`, and `OWNER/.R.EPOXY.Z.`.

There is no way PrivPage can now where the dot is.

**Comment by j8r** [comment]
No, because the site will be the same for `OWNER/REPOXYZ` and `OWNER/REPO.XYZ`, but also anywhere the dot is, like `OWNER/R.EPOXYZ`, and `OWNER/.R.EPOXY.Z.`.

There is no way PrivPage can know where the dot is in the repo name from the subdomain name.
