### ISSUE TITLE
Invalid certificate

### ISSUE THREAD

**Issue by kawamoto-taku-13** [Priv-Page/privpage#12]
I cannot connect to PrivPage because the certificate has expired.

The same is true not only for the repository you created, but also for the links listed as samples.

- https://priv-page--test.github.privpage.net
- https://priv-page--test--latest.github.privpage.net
- https://priv-page--test-public.github.privpage.net

**Comment by j8r** [comment]
I did renew them, but the .cer was not copied :/

Thanks, done!

Looks like some people are still using the service :)

**Comment by kaskarn** [comment]
> Looks like some people are still using the service :)

Very much so, we run our small lab's documentation platform using privpage -- it's been really helpful!
