### ISSUE TITLE
Serve index.html on URLs without filename

### ISSUE THREAD

**Issue by B3QL** [Priv-Page/privpage#13]
Hi, really cool project!

During the setup I found some strange behaviour.

Going to the 
https://username--projectname.github.privpage.net/ root domain 
the content of `index.html` is served properly. However on the subdirectory level I get the empty 302 response without redirect url in header.This results in empty white page whenever I try to access 
https://username--projectname.github.privpage.net/mysubdir 
On the other hand https://username--projectname.github.privpage.net/mysubdir/index.html works like a charm.

**Comment by B3QL** [comment]
@j8r I also try to host the private docs (which has a subdirs).

IMO it can be assumed if the URL does not contain file extension then return the content of `index.html` which removes the need for an extra API call.

In the use-case of serving documentation (static files), I see no reason to serve the files without file extensions.

**Comment by j8r** [comment]
One use case to serve a file with no extension is to have a binary blob available for download.

**Comment by B3QL** [comment]
> I don't think it is really worth it, nor a big deal, considering this project is supposed to serve documentation/development related sites.

IMO to serve the BLOB you can always put the `.bin` extension.

But overall really depends on project goals - if it's documentation oriented then the proposed change will be beneficial if not then the ticket can be closed.

**Comment by j8r** [comment]
Also, what's `GET mysite.com/SomePage`? Is it `mysite.com/SomePage/index.html` or `mysite.com/SomePage.html`? GitHub Pages also rewrite `mysite.com/SomePage.html` to `mysite.com/SomePage`. One may want to have this behavior too.

All this things complicates the applications, and more important, will slow down the response time.

It's not a good idea to assume things that are 99% true, because here we don't know at all what people serve with their sites - they can do everything.

**Comment by j8r** [comment]
Still, thanks for the proposal!

The goal of this project is aimed to have a simple, quick way to have a site working. We could have a cache, advanced features, but for now it is not worth it for little, private dev sites. Even more so that it cost me few $$ per month.

**Comment by B3QL** [comment]
For travelers from the future that uses `mkdocs` for Python project.

The solution is to pass the `--no-directory-urls` flag which will create html files instead of creating new directories for pretty URLs.
```
mkdocs gh-deploy -b privpage --no-directory-urls
```
