### ISSUE TITLE
Example usage with RTD or React

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [Priv-Page/privpage#14]
Hey! Awesome project. Just some recommendation so this receives more attention

Would love to see you make a tutorial in a separate repository for hosting RTD themed documentation hosted on GitHub pages. Additionally, people using React or an SPA would love to do this. Some resources that'd be helpful:

- A RTD that's already setup: https://github.com/pydanny/cookiecutter-django
- A [SO answer](https://stackoverflow.com/questions/62683329/how-to-self-host-read-the-docs-using-github-pages) / blog post (https://tech.michaelaltfield.net/2020/07/18/sphinx-rtd-github-pages-1/) that can build the RTD in GitHub CI / Travis CI and thus publish it to GitHub pages.

For React, use this:
- https://github.com/gitname/react-gh-pages

Let me know if you need help or if you want me to do it! Cheers!

**Comment by j8r** [comment]
I won't be against. It should be as simple as possible, to be the base of everyone's code. Nothing stops to have multiple examples though.

I'll create a new repository for this.

**Comment by j8r** [comment]
Sorry I totally forgot about that, created https://github.com/Priv-Page/examples
