### ISSUE TITLE
Not renewing expiring `privpage.net` domain on 22th April 2022

### ISSUE THREAD

**Issue by j8r** [Priv-Page/privpage#18]
The `privpage.net` domain will expire on 22th April 2022.

I won't renew because I have no incentive, nor really want to continue spending more time and money to maintain for free the server. I have moved on other projects.

Thanks to all users! The project turned out to work quite well. I hope GitHub will support this feature natively in the future, for free and everyone. Of course it remains possible self-host this project on your server.

**Comment by charlielito** [comment]
Did you already shut down the server?

**Comment by j8r** [comment]
The server is indeed no longer functional, the process has crashed. I think that's because the tokens are no longer valid.
The certificate will have expired in a week anyway,

**Comment by MPJHorner** [comment]
Oh no my documentation 😢 

Anyone got workaround or alternative service?

**Comment by charlielito** [comment]
Do you have any guide on how to self-host this? I am trying locally without success just compiling the code and running the server with defaults

**Comment by j8r** [comment]
You'll need:
- A GitHub App or OAuth App. Can be created in your account or in your organization in `developer settings`.
- Get the oauth tokens and set the environment variables (see the README.md). 
- give the permissions to access your repositories
- a reverse proxy, like Caddy, to have https
- `crystal` to compile the project.

I think you should be good after that.

**Comment by YoSev** [comment]
I developed a selfhosted alternative with a similar idea as this service is shut down - i hope it's okay to post that here.
https://github.com/john-dev/private-ghp

**Comment by B3QL** [comment]
Thanks @j8r for developing the project and providing the infrastructure!

**Comment by KorigamiK** [comment]
It was a pleasure using this service. Fun times 🥇

**Comment by amielnoyp** [comment]
Hi ,
Is it possible to use it now?
Or it's finnaly not not possible?

**Comment by KorigamiK** [comment]
> Hi ,
> Is it possible to use it now?
> Or it's finnaly not not possible?

You have the source code so you can host it yourself, however the domain is still not renewing.

**Comment by charlielito** [comment]
> I developed a selfhosted alternative with a similar idea as this service is shut down - i hope it's okay to post that here. https://github.com/john-dev/private-ghp

I've been using this alternative for the last year in it is working without problems

**Comment by j8r** [comment]
You can self-host both projects, as you prefer.
