### ISSUE TITLE
Public repositories not served

### ISSUE THREAD

**Issue by Veetaha** [Priv-Page/privpage#3]
Is this intended that this error message is used upon any error condition?
I see this message even when I misspell the link to the repo and when someone who doesn't have access to the repo follows the link?
It is a bit misleading, though not critical.
It think it would be more intuitive to issue something like:
```
The repository doesn't exist, or it is public or you don't have access to it.
```

Also, privpage is awesome, thanks for sharing it :D

**Comment by j8r** [comment]
Thanks @Veetaha :)

Yes, this error should be only shown when trying to serve a public repository, because there is already GitHub Pages for that purpose of course.

It is possible to have a different error for that purpose.

**Comment by Veetaha** [comment]
Wow, thanks for such a rapid patch!
