### ISSUE TITLE
Suggestion: File Inclusion Specification

### ISSUE THREAD

**Issue by afspies** [Priv-Page/privpage#4]
It seems that by default not all files in the privpage branch are included, even if they are linked within index.html. 

Perhaps allow users to add a configuration file which sets the paths for file / folder inclusions relevant to the rendering of the page?

**Comment by j8r** [comment]
Hello, what do you mean by "not all files in the privpage branch are included", have you an example?

**Comment by afspies** [comment]
Hi,

I just tried using a jekyll based template (https://github.com/barryclark/jekyll-now) with the folder structure:

<img width="235" alt="Screenshot 2020-06-17 at 20 16 05" src="https://user-images.githubusercontent.com/14139469/84940238-74aa5a80-b0d7-11ea-98ca-305c94ac20f0.png">

which doesn't render properly
![Screenshot 2020-06-17 at 20 25 28](https://user-images.githubusercontent.com/14139469/84941060-b1c31c80-b0d8-11ea-853c-2ef52e345808.png)

Though perhaps this is due to Jekyll doing something naughty with paths...

**Comment by j8r** [comment]
Ha, ok that's normal. GitHub Pages includes a Jekyll builder, which evaluates this templates. Th site is automatically built by GitHub.

PrivPages has no such thing, you have to build yourself, for example by adding a "build" step to your CI.
A "publish" step can also be added to push the built page to the `privpage` branch.

**Comment by afspies** [comment]
Ah you're completely right - I was messing up the build process without realizing >.< 

Thank you!
