### ISSUE TITLE
Invalid SSL Certificate?

### ISSUE THREAD

**Issue by MichelML** [Priv-Page/privpage#6]
@j8r can you please check your SSL cert? It seems like chrome now blocks entirely pages with invalid certificate.

**Comment by j8r** [comment]
I don't know, the certificate is still valid:
```sh
openssl s_client \
        -showcerts \
        -connect privpage.net:443 < /dev/null 2>&1 \
    | openssl x509 -noout -text | grep Validity -A 2
```
Result:
```
        Validity
            Not Before: Aug 21 12:51:48 2020 GMT
            Not After : Nov 19 12:51:48 2020 GMT
```

It is a HSTS related error, see https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security for more information.
Try to directly reach the URL with **https://**.

**Comment by MichelML** [comment]
@j8r I didn't post the screenshot of the invalid certificate, but I can confirm it was part of the problem and it was occurring via https access - I don't know what you did in the meantime, but I can't reproduce the error.

**Comment by j8r** [comment]
I did nothing.
It was either related to the client (your browser/OS), or something between it and the server, like a proxy or even a man-in-the-middle style attack.

**Comment by MichelML** [comment]
No worries :+1:
