### ISSUE TITLE
Files above 1MB receive 403 error

### ISSUE THREAD

**Issue by morinted** [Priv-Page/privpage#7]
I was hoping to use privpage to deploy a storybook instance, but some of the built files exceed 1MB and despite my best efforts I can't get them to split further.

Here is the network request response:

```
{"message":"This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.","errors":[{"resource":"Blob","field":"data","code":"too_large"}],"documentation_url":"https://docs.github.com/rest/reference/repos#get-repository-content"}
```

**Comment by j8r** [comment]
Hi @morinted , as stated by the error, this is a GitHub API error. Nothing I can do, sorry.

**Comment by j8r** [comment]
Maybe it could be possible to use the Blob API: https://developer.github.com/v3/git/blobs/#get-a-blob, but then, I guess, the browser will ask to download the file.
Is it what you have in mind?

**Comment by j8r** [comment]
Hum, not sure it is an option, because we have to get the file's SHA before using the Blob API :confused:

**Comment by morinted** [comment]
That's fair! I did end up getting my storybook to build below 1MB using  both the webpackManager and webpackFinal config options and setting size limits on the splitChunks plugin.

I suppose that for now this'll just have to be a known limitation.

**Comment by hadim** [comment]
I also see this issue when serving jupyter notebooks converted using mkdocs and nbconvert.
