### ISSUE TITLE
Unable to use iFrame

### ISSUE THREAD

**Issue by morinted** [Priv-Page/privpage#8]
When trying to use an iFrame in my storybook site hosted on privpage, I receive the following error:

> Refused to display 'https://owner--repo.github.privpage.net/iframe.html?id=*&viewMode=story' in a frame because it set 'X-Frame-Options' to 'deny'.

If this is something we have control over, it would probably be good to set it to `sameorigin` instead.

**Comment by morinted** [comment]
Ah, I see it here: https://github.com/Priv-Page/privpage/blob/d4c9e39e7500e04726f920d049361c5144811f00/src/privpage.cr#L17

I believe sameorigin also protects against click-jacking, while still allowing iFrame use.

**Comment by j8r** [comment]
Can do!
According to https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy, the origin will differ for each different subdomain.

I have some security concerns by reading https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options, which says that the spec is up to the browser to be interpreted, and also point to a Bugzilla bug.

Therefore, I will also add https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors, with the `self` value, which is more recent.

**Comment by j8r** [comment]
Should be good now @morinted .
