### ISSUE TITLE
Does Privpage support mixed case organisation names / repo names?

### ISSUE THREAD

**Issue by n00bsys0p** [Priv-Page/privpage#9]
Hi,

I've been trying to set this up for one of our organization's repositories and it's consistently giving me `Invalid repository: orgname/repo-name-here (Not Found).`

I've got it running already for a different organisation, and the only difference between these two that I can see is that the working organisation's name and repository name are all in lower case (orgname/repo-name-here), and the non-working one has both a mixture of upper and lower case (OrgName/Repo-Name-Here). However if I access the repository via its URL and enter the whole thing in lower case, it does resolve to the correct location.

Are you able to advise what may be causing this? Is there any workaround?

**Comment by j8r** [comment]
Hello @n00bsys0p , as any domains, there is no difference between up/down case. Here for example, I just got it working for `Priv-Page/test-One`, which is private in this organization.

https://orgname--repo-name-here.github.privpage.net is not working for you?

**Comment by j8r** [comment]
This error can also be related to a permission error. For security, GitHub doesn't tell if the repo is not existent, or not accessible due to lack of permissions.
Be sure to have added the [Priv-Page](https://github.com/apps/priv-page) application to the organization, and allowed the access to the repository in question.

**Comment by n00bsys0p** [comment]
I had indeed forgotten to give the app access to the repository. That was exactly the issue. Apologies for wasting your time!
